
services:
  go-app:
    container_name: go-app
    image: products-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - products_db
  products_db:
    container_name: products_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}